using System.Globalization;
using System.Net;
using System.Text;

namespace LegacyLens.Application.Audit;

public sealed class AuditReportExportService(
    ILegacyAuditMarkdownFormatter markdownFormatter) : IAuditReportExportService
{
    public string ExportMarkdown(LegacyAuditReport report)
    {
        if (!string.IsNullOrWhiteSpace(report.Markdown))
            return report.Markdown;

        return markdownFormatter.Format(report);
    }

    public string ExportHtml(LegacyAuditReport report)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!doctype html>");
        sb.AppendLine("<html lang=\"en\">");
        sb.AppendLine("<head>");
        sb.AppendLine("<meta charset=\"utf-8\">");
        sb.AppendLine("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">");
        sb.AppendLine("<title>Legacy .NET Audit Report</title>");
        sb.AppendLine("<style>");
        sb.AppendLine("""
            :root{color-scheme:light;font-family:Inter,Segoe UI,Arial,sans-serif;color:#111827;background:#f5f6f8}
            body{margin:0;padding:2rem}
            main{max-width:1100px;margin:0 auto;background:white;border:1px solid #e5e7eb;border-radius:18px;padding:2rem;box-shadow:0 16px 50px rgba(15,23,42,.08)}
            h1{margin:0 0 .4rem;font-size:2rem;letter-spacing:-.03em}
            h2{margin-top:2rem;border-bottom:1px solid #e5e7eb;padding-bottom:.45rem}
            h3{margin-bottom:.35rem}
            .muted{color:#6b7280}
            .meta{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:.75rem;margin:1rem 0}
            .meta div,.card{border:1px solid #e5e7eb;border-radius:12px;background:#f9fafb;padding:.85rem}
            .meta span{display:block;color:#6b7280;font-size:.8rem;text-transform:uppercase;letter-spacing:.06em}
            .badge{display:inline-block;border-radius:999px;background:#eef2ff;color:#3730a3;font-size:.78rem;font-weight:700;padding:.2rem .55rem}
            .severity-high,.severity-critical{background:#fee2e2;color:#991b1b}
            .severity-warning,.severity-medium{background:#fef3c7;color:#92400e}
            .severity-info,.severity-low{background:#dbeafe;color:#1d4ed8}
            pre{white-space:pre-wrap;overflow:auto;background:#0f172a;color:#d1d5db;border-radius:12px;padding:1rem}
            code{font-family:ui-monospace,SFMono-Regular,Consolas,monospace}
            ul{padding-left:1.35rem}
            .footer{margin-top:2rem;color:#6b7280;font-size:.9rem}
            """);
        sb.AppendLine("</style>");
        sb.AppendLine("</head>");
        sb.AppendLine("<body>");
        sb.AppendLine("<main>");
        sb.AppendLine("<h1>Legacy .NET Audit Report</h1>");
        sb.AppendLine("<p class=\"muted\">Self-contained export generated by LegacyLens.</p>");

        AppendMeta(sb, report);
        AppendSummary(sb, report);
        AppendWorkspace(sb, report.WorkspaceSummary);
        AppendTechnologySignals(sb, report.TechnologySignals);
        AppendArchitectureSignals(sb, report.ArchitectureSignals);
        AppendRiskFindings(sb, report.RiskFindings);
        AppendRoslyn(sb, report.RoslynSummary);
        AppendDependencyInjection(sb, report.DependencyInjectionSummary);
        AppendGpuSearch(sb, report.GpuSearchSummary);
        AppendNextSteps(sb, report.RecommendedNextSteps);

        if (!string.IsNullOrWhiteSpace(report.LlmSummary))
        {
            sb.AppendLine("<h2>LLM Summary</h2>");
            sb.AppendLine($"<div class=\"card\">{Paragraphs(report.LlmSummary)}</div>");
        }

        sb.AppendLine("<h2>Markdown Source</h2>");
        sb.AppendLine($"<pre>{Html(ExportMarkdown(report))}</pre>");
        sb.AppendLine("<p class=\"footer\">Exports are local files and may contain repository paths, code snippets, findings, and optional LLM summaries. Review before sharing externally.</p>");
        sb.AppendLine("</main>");
        sb.AppendLine("</body>");
        sb.AppendLine("</html>");
        return sb.ToString();
    }

    public string BuildFileName(LegacyAuditReport report, string extension)
    {
        var ext = extension.TrimStart('.');
        var repoFolder = report.RepoPath
            .TrimEnd('\\', '/')
            .Split(['\\', '/'], StringSplitOptions.RemoveEmptyEntries)
            .LastOrDefault();

        if (string.IsNullOrWhiteSpace(repoFolder))
            repoFolder = "repository";

        var safeRepo = SanitizeFileName(repoFolder);
        var stamp = report.GeneratedAtUtc.UtcDateTime.ToString("yyyyMMdd-HHmmss", CultureInfo.InvariantCulture);
        return $"legacy-audit-{safeRepo}-{stamp}.{ext}";
    }

    private static void AppendMeta(StringBuilder sb, LegacyAuditReport report)
    {
        sb.AppendLine("<section class=\"meta\">");
        Meta(sb, "Report ID", report.ReportId);
        Meta(sb, "Repository", report.RepoPath);
        Meta(sb, "Generated", report.GeneratedAtUtc.ToString("O"));
        Meta(sb, "Risk findings", report.RiskFindings.Count.ToString(CultureInfo.InvariantCulture));
        sb.AppendLine("</section>");
    }

    private static void AppendSummary(StringBuilder sb, LegacyAuditReport report)
    {
        sb.AppendLine("<h2>Summary</h2>");
        sb.AppendLine($"<div class=\"card\">{Paragraphs(report.Summary)}</div>");
    }

    private static void AppendWorkspace(StringBuilder sb, AuditWorkspaceSummary workspace)
    {
        sb.AppendLine("<h2>Workspace</h2>");
        sb.AppendLine("<div class=\"card\"><ul>");
        sb.AppendLine($"<li><strong>Selected:</strong> {Html(workspace.SelectedWorkspacePath ?? "No workspace file found.")} {Html(workspace.SelectedWorkspaceKind?.ToString() ?? string.Empty)}</li>");
        sb.AppendLine($"<li><strong>Candidates:</strong> {workspace.TotalCandidates} ({workspace.SlnxCount} .slnx, {workspace.SlnCount} .sln, {workspace.CsprojCount} .csproj)</li>");
        foreach (var warning in workspace.Warnings)
            sb.AppendLine($"<li>⚠ {Html(warning)}</li>");
        sb.AppendLine("</ul></div>");
    }

    private static void AppendTechnologySignals(StringBuilder sb, IReadOnlyList<TechnologySignal> signals)
    {
        sb.AppendLine("<h2>Technology Signals</h2>");
        if (signals.Count == 0)
        {
            sb.AppendLine("<p class=\"muted\">No technology signals detected.</p>");
            return;
        }

        foreach (var signal in signals)
        {
            sb.AppendLine("<article class=\"card\">");
            sb.AppendLine($"<span class=\"badge\">{Html(signal.Category)}</span> <span class=\"badge\">{Html(signal.Confidence)}</span>");
            sb.AppendLine($"<h3>{Html(signal.Name)}</h3>");
            if (!string.IsNullOrWhiteSpace(signal.FilePath))
                sb.AppendLine($"<p><code>{Html(signal.FilePath)}</code></p>");
            sb.AppendLine($"<p>{Html(signal.Evidence)}</p>");
            sb.AppendLine("</article>");
        }
    }

    private static void AppendArchitectureSignals(StringBuilder sb, IReadOnlyList<ArchitectureSignal> signals)
    {
        sb.AppendLine("<h2>Architecture Signals</h2>");
        if (signals.Count == 0)
        {
            sb.AppendLine("<p class=\"muted\">No architecture signals detected.</p>");
            return;
        }

        foreach (var signal in signals)
        {
            sb.AppendLine("<article class=\"card\">");
            sb.AppendLine($"<h3>{Html(signal.Name)}</h3>");
            sb.AppendLine($"<p>{Html(signal.Message)}</p>");
            sb.AppendLine($"<p class=\"muted\">{Html(signal.Evidence)} (confidence: {Html(signal.Confidence)})</p>");
            sb.AppendLine("</article>");
        }
    }

    private static void AppendRiskFindings(StringBuilder sb, IReadOnlyList<AuditFinding> findings)
    {
        sb.AppendLine("<h2>Risk Findings</h2>");
        if (findings.Count == 0)
        {
            sb.AppendLine("<p class=\"muted\">No risk findings detected.</p>");
            return;
        }

        foreach (var finding in findings)
        {
            var severityClass = $"severity-{finding.Severity.ToLowerInvariant()}";
            sb.AppendLine("<article class=\"card\">");
            sb.AppendLine($"<span class=\"badge {Html(severityClass)}\">{Html(finding.Severity)}</span> <code>{Html(finding.Code)}</code>");
            sb.AppendLine($"<h3>{Html(finding.Title)}</h3>");
            if (!string.IsNullOrWhiteSpace(finding.FilePath))
                sb.AppendLine($"<p><code>{Html(finding.FilePath)}{(finding.Line.HasValue ? ":" + finding.Line.Value.ToString(CultureInfo.InvariantCulture) : string.Empty)}</code></p>");
            sb.AppendLine($"<p>{Html(finding.Message)}</p>");
            if (!string.IsNullOrWhiteSpace(finding.Evidence))
                sb.AppendLine($"<p class=\"muted\"><em>Evidence: {Html(finding.Evidence)}</em></p>");
            sb.AppendLine("</article>");
        }
    }

    private static void AppendRoslyn(StringBuilder sb, AuditRoslynSummary? roslyn)
    {
        sb.AppendLine("<h2>Roslyn Summary</h2>");
        if (roslyn is null)
        {
            sb.AppendLine("<p class=\"muted\">Roslyn analysis was not requested.</p>");
            return;
        }

        sb.AppendLine("<div class=\"card\"><ul>");
        sb.AppendLine($"<li><strong>Workspace loaded:</strong> {roslyn.WorkspaceLoaded}</li>");
        sb.AppendLine($"<li><strong>Workspace:</strong> {Html(roslyn.WorkspacePath ?? "n/a")}</li>");
        sb.AppendLine($"<li><strong>Projects:</strong> {roslyn.ProjectCount}; <strong>Documents:</strong> {roslyn.DocumentCount}; <strong>Symbols:</strong> {roslyn.SymbolCount}</li>");
        if (!string.IsNullOrWhiteSpace(roslyn.ErrorMessage))
            sb.AppendLine($"<li><strong>Error:</strong> {Html(roslyn.ErrorMessage)}</li>");
        foreach (var warning in roslyn.Warnings)
            sb.AppendLine($"<li>⚠ {Html(warning)}</li>");
        sb.AppendLine("</ul></div>");
    }

    private static void AppendDependencyInjection(StringBuilder sb, AuditDependencyInjectionSummary? di)
    {
        sb.AppendLine("<h2>Dependency Injection Summary</h2>");
        if (di is null)
        {
            sb.AppendLine("<p class=\"muted\">DI analysis was not requested.</p>");
            return;
        }

        sb.AppendLine("<div class=\"card\"><ul>");
        sb.AppendLine($"<li>Registrations: {di.RegistrationCount}</li>");
        sb.AppendLine($"<li>Constructor dependencies: {di.ConstructorDependencyCount}</li>");
        sb.AppendLine($"<li>Findings: {di.FindingCount}</li>");
        sb.AppendLine("</ul></div>");
    }

    private static void AppendGpuSearch(StringBuilder sb, AuditGpuSearchSummary? gpuSearch)
    {
        sb.AppendLine("<h2>gpu-search Signal Scan</h2>");
        if (gpuSearch is null)
        {
            sb.AppendLine("<p class=\"muted\">gpu-search analysis was not requested.</p>");
            return;
        }

        sb.AppendLine("<div class=\"card\"><ul>");
        sb.AppendLine($"<li>Available: {gpuSearch.WasAvailable}</li>");
        sb.AppendLine($"<li>Mode: {(gpuSearch.UsedSignalScan ? "Signal scan" : "Individual queries")}</li>");
        sb.AppendLine($"<li>Total matches: {gpuSearch.TotalResults}</li>");
        if (!string.IsNullOrWhiteSpace(gpuSearch.ErrorMessage))
            sb.AppendLine($"<li>Error: {Html(gpuSearch.ErrorMessage)}</li>");
        sb.AppendLine("</ul></div>");

        foreach (var result in gpuSearch.Results.Take(50))
        {
            sb.AppendLine("<article class=\"card\">");
            sb.AppendLine($"<p><code>{Html(result.Query)}</code> — <code>{Html(result.FilePath ?? "unknown")}{(result.Line.HasValue ? ":" + result.Line.Value.ToString(CultureInfo.InvariantCulture) : string.Empty)}</code></p>");
            if (!string.IsNullOrWhiteSpace(result.Snippet))
                sb.AppendLine($"<pre>{Html(result.Snippet)}</pre>");
            sb.AppendLine("</article>");
        }
    }

    private static void AppendNextSteps(StringBuilder sb, IReadOnlyList<string> steps)
    {
        sb.AppendLine("<h2>Recommended Next Steps</h2>");
        if (steps.Count == 0)
        {
            sb.AppendLine("<p class=\"muted\">No recommendations generated.</p>");
            return;
        }

        sb.AppendLine("<ul>");
        foreach (var step in steps)
            sb.AppendLine($"<li>{Html(step)}</li>");
        sb.AppendLine("</ul>");
    }

    private static void Meta(StringBuilder sb, string label, string value)
        => sb.AppendLine($"<div><span>{Html(label)}</span><strong>{Html(value)}</strong></div>");

    private static string Paragraphs(string value)
        => string.Join(
            Environment.NewLine,
            value.Split(["\r\n", "\n"], StringSplitOptions.None)
                .Where(line => !string.IsNullOrWhiteSpace(line))
                .Select(line => $"<p>{Html(line)}</p>"));

    private static string Html(string value) => WebUtility.HtmlEncode(value);

    private static string SanitizeFileName(string value)
    {
        var invalid = Path.GetInvalidFileNameChars()
            .Concat(['<', '>', ':', '"', '/', '\\', '|', '?', '*'])
            .Distinct()
            .ToArray();
        var sanitized = new string(value
            .Select(ch => invalid.Contains(ch) || char.IsWhiteSpace(ch) ? '-' : ch)
            .ToArray());
        sanitized = sanitized.Trim('-', '.');
        if (sanitized.Length > 80)
            sanitized = sanitized[..80].Trim('-', '.');
        return string.IsNullOrWhiteSpace(sanitized) ? "repository" : sanitized;
    }
}
